### ISSUE TITLE
How can I display the HTML code blocks without overflowing and containing the same background

### ISSUE THREAD

**Issue by akashravichandran** [piharpi/jekyll-klise#10]
**Describe the bug**
I converted a python notebook file to basic html template using the nbconvert support from jupyter and when I use that basic template to render my page, the codes and some contents were overflowing, to tackle that, I used the overflow table class, which resolved the overflow but the overflowed portion is not containing the same background. 

**Screenshots**
![image](https://user-images.githubusercontent.com/15701829/85205578-d407a500-b339-11ea-8292-f29a1da0f990.png)

**Link to the code**
https://github.com/akashravichandran/akashravichandran.github.io/blob/master/_posts/jovianml/2020-06-02-insurance_linear_regression.html

**Link to the rendered page**
https://github.com/akashravichandran/akashravichandran.github.io/blob/master/_posts/jovianml/2020-06-02-insurance_linear_regression.html

**Additional context**
Any help regarding this issue is much appreciated. Thanks in advance.

**Comment by piharpi** [comment]
Hi @akashravichandran, 
use the [markdown](https://kramdown.gettalong.org/syntax.html#fenced-code-blocks) format to write fenced code block instead of plain tags, Jekyll automatically generate fenced code block using `<pre>`, and already styled with our theme. 

The problem is because Jekyll and Jupyter have different formats.  

The problems

**Comment by akashravichandran** [comment]
I found a way by which I can render the jupyter html file properly. Putting the solution here, if in case some one requires it. 


Replace this
`<div class=" highlight hl-ipython3>`
by:
`<div class=" highlight hl-ipython3 overflow-table">`


Replace this
```
<div class="output_html rendered_html output_subarea output_execute_result">
<div>
```
by:
```
<div class="output_html rendered_html output_subarea output_execute_result">
<div class="overflow-table">
```


Replace this
`<div class="output_text output_subarea output_execute_result">`
by:
`<div class="output_text output_subarea output_execute_result overflow-table">`


Replace this
`<div class="output_subarea output_stream output_stdout output_text">`
by:
`<div class="output_subarea output_stream output_stdout output_text overflow-table">`
