### ISSUE TITLE
Not able to view Disqus comment bar

### ISSUE THREAD

**Issue by syedjawadakhtar** [piharpi/jekyll-klise#14]
I have edited `post.html` and also added `disqus.html` in the `_includes` folder. Yet I'm not able to view the Disqus comment section on my blog post.

`post.html`
```
{% if site.disqus.shortname %}
  	{% include disqus.html %}
 {% endif %}
```

I have followed many tutorials to add Disqus in Jekyll websites. The latest one which seemed working for the majority of the people: [https://desiredpersona.com/disqus-comments-jekyll/](https://desiredpersona.com/disqus-comments-jekyll/)

Link to my repo: [Link](https://github.com/syedjawadakhtar/site-jawadsblog.netlify.app)
Any help with this regard would be helpful!

**Comment by piharpi** [comment]
@syedjawadakhtar be sure you set the build command to `JEKYLL_ENV=production jekyll build`
if your using netlify go head and change at `/settings/deploys#continuous-deployment`
![image](https://user-images.githubusercontent.com/20749264/85970816-c1563580-b9f5-11ea-855b-99a85a79f2e9.png)
for more information check this out https://jekyllrb.com/docs/configuration/environments/

**Comment by syedjawadakhtar** [comment]
Thanks @piharpi for the solution. I'm seeing into it right. Actually I'm new to Jekyll and putting HTML scripts at the right place.

I changed the settings in the netlify and used the command for building the website as well. But I think I'm doing something really noob that's making it not to work.

I think it is with the placement of the `include` statements in the `post.html`. Because after commenting some lines in that document, even I don't see the Disqus comment box but `-->` (end of HTML comment) can be seen at the end of my post. 
[Attached Image]
![comment](https://user-images.githubusercontent.com/22319639/86153600-91a34c80-bb1f-11ea-80e7-06bbf48e1d03.png)
