### ISSUE TITLE
Add pagination

### ISSUE THREAD

**Issue by huzaima** [piharpi/jekyll-klise#20]
**Is your feature request related to a problem? Please describe.**
Unable to add pagination

**Describe the solution you'd like**
Pagination supported on home page in recent posts

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by piharpi** [comment]
@huzaima currently the pagination is not fully supported, it just my experiment and I forgot to ignore the file

**Comment by huzaima** [comment]
Thanks, @piharpi. I managed to implement it using Jekyll paginate plugin.

**Comment by piharpi** [comment]
You're welcome
