### ISSUE TITLE
Change Symbol of Dark Mode

### ISSUE THREAD

**Issue by abhisheknaiidu** [piharpi/jekyll-klise#21]
**Is your feature request related to a problem? Please describe.**
Right now, the toggle button of Dark Mode is the same on both Day and Night Mode.

**Describe the solution you'd like**
It should be like, showing `Moon` icon on Night and `Sun` icon on Day Mode

**Comment by piharpi** [comment]
Thank you for the issue, the reason I use the same icon is for the simplicity of the theme, I'm sure when someone uses the theme; they will definitely customize with their own style

**Comment by abhisheknaiidu** [comment]
> Thank you for the issue, the reason I use the same icon is for the simplicity of the theme, I'm sure when someone uses the theme; they will definitely customize with their own style

@piharpi That makes sense man, btw nice work Man!
I also want to ask you, are we allowed to add Google Adsense to this Blog??

**Comment by piharpi** [comment]
Yes, of course, You allowed adding Google Adsense or anything else to your own web using this template
