### ISSUE TITLE
Search bar on Safari

### ISSUE THREAD

**Issue by fi0** [piharpi/jekyll-klise#22]
https://klise.now.sh/archive/
Safari Version 13.1.2 (15609.3.5.1.3)
macOS 10.15.6 (19G2021)

![image](https://user-images.githubusercontent.com/25412990/92223263-ce4e4400-eed2-11ea-9681-932bf6060931.png)

**Comment by piharpi** [comment]
Thanks for the issue, it should be like this
![image](https://user-images.githubusercontent.com/20749264/92244217-d3b88800-eeec-11ea-8757-a6055d4dcff1.png)

gonna fix soon :)

**Comment by fahmiirsyadk** [comment]
@fi0 @piharpi 
I created a PR to fix that issue. 
check this out #23 


Tested on:  **MacOS 10.15.6 Safari Version 13.1.2 (15609.3.5.1.3)**
preview: 
<img width="1226" alt="Screen Shot 2020-09-06 at 14 57 31" src="https://user-images.githubusercontent.com/17546686/92321116-97526c80-f051-11ea-940f-7e6c3808715b.png">

**Comment by piharpi** [comment]
@fahmiirsyadk good work, thanks
