### ISSUE TITLE
Flash of dark mode styling when using light mode

### ISSUE THREAD

**Issue by nickyvanurk** [piharpi/jekyll-klise#25]
**Describe the bug**
When you enable light mode, and click a link/refresh the page, you will see a flash of dark mode styles website before it turns light. This happens everytime you click any link so it's kinda of annoying if you are browsing the site.

**To Reproduce**
1. Go to homepage
2. Click on sun icon to enable light mode
3. Click any link

**Expected behavior**
Light mode to stay light

**Comment by piharpi** [comment]
Thanks for the issue.
