### ISSUE TITLE
General question - how do I change Font?

### ISSUE THREAD

**Issue by rahulgadre** [piharpi/jekyll-klise#26]
Thank you for this template. I have a general question about changing the font. I see that the current one is set to Roboto. How do I change it to a different font? I am new to Jekyll so any help here would be helpful.

Best,
Rahul

**Comment by piharpi** [comment]
Go to `yoursite/_sass/main.scss `, replace with your own
```scss
// Fonts preferences
$sans-family: Roboto, sans-serif;
$mono-family: Consolas, monospace;
$base-font-size: 16px;
$medium-font-size: $base-font-size * 0.938;
$small-font-size: $base-font-size * 0.875;
$base-line-height: 1.85;
``` 
For example 
https://github.com/piharpi/jekyll-klise/blob/master/_sass/main.scss

**Comment by rahulgadre** [comment]
That worked. Thank you for your reply.

Best,
Rahul

**Comment by piharpi** [comment]
You're welcome

**Comment by abhisheknaiidu** [comment]
> Go to `yoursite/_sass/main.scss `, change the values with your own
> 
> ```css-scss
> // Fonts preferences
> $sans-family: Roboto, sans-serif;
> $mono-family: Consolas, monospace;
> $base-font-size: 16px;
> $medium-font-size: $base-font-size * 0.938;
> $small-font-size: $base-font-size * 0.875;
> $base-line-height: 1.85;
> ```
> 
> For example
> https://github.com/piharpi/jekyll-klise/blob/master/_sass/main.scss

Hey hi @piharpi , I actually changed the font to `Fira Code`, but it worked just for Chrome and Firefox, for Safari and Mobile Version, it's just showing normal Font's, do know what to do?

**Comment by abhisheknaiidu** [comment]
> > Go to `yoursite/_sass/main.scss `, change the values with your own
> > ```
> > // Fonts preferences
> > $sans-family: Roboto, sans-serif;
> > $mono-family: Consolas, monospace;
> > $base-font-size: 16px;
> > $medium-font-size: $base-font-size * 0.938;
> > $small-font-size: $base-font-size * 0.875;
> > $base-line-height: 1.85;
> > ```
> > 
> > 
> > For example
> > https://github.com/piharpi/jekyll-klise/blob/master/_sass/main.scss
> 
> Hey hi @piharpi , I actually changed the font to `Fira Code`, but it worked just for Chrome and Firefox, for Safari and Mobile Version, it's just showing normal Font's, do know what to do?

It worked using some CSS type faces from [here](https://github.com/tonsky/FiraCode/issues/18#issuecomment-382254761)!
