### ISSUE TITLE
github.io

### ISSUE THREAD

**Issue by mamutal91** [piharpi/jekyll-klise#29]
How do I host the site on github.io?

**Comment by piharpi** [comment]
Click **use this template** button
![image](https://user-images.githubusercontent.com/20749264/99921636-36882580-2d5e-11eb-9d06-35f490b31d1b.png)

Create your own repository, name it **your-username.github.io**, then click **create a repository from template** button
![image](https://user-images.githubusercontent.com/20749264/99921631-2a9c6380-2d5e-11eb-9e63-27bada77d692.png)

Go to Repository Setting -> Options -> **GitHub Pages section**
![image](https://user-images.githubusercontent.com/20749264/99921932-3be66f80-2d60-11eb-8d8e-f3c44ae4ddb4.png)

Click the link and your site will show up.

For more information refer to https://pages.github.com/ happy reading.
