### ISSUE TITLE
Thumbnail add « facebook_username »

### ISSUE THREAD

**Issue by famascl3m** [piharpi/jekyll-klise#30]
When i share the site url or an article, the thumbnail title display a misterious « facebook_username »

I tried to add a « # » before the facebook_username line in the _config.yml but it was no change

![E064640B-A7FC-444A-96A2-1F1AADCACDAA](https://user-images.githubusercontent.com/40993037/100938733-8650b480-34f5-11eb-889a-566ace7ab762.jpeg)
![68115673-5C4F-4331-AA78-9F03DD5ECC3F](https://user-images.githubusercontent.com/40993037/100938736-8781e180-34f5-11eb-951c-90b4fa5e523f.jpeg)

**Comment by piharpi** [comment]
Hello @famascl3m thanks for reporting, to solve, you need replace `site.author.facebook` to `site.author.name` at line 62 and 68 in `_includes/header.html` file 
![image](https://user-images.githubusercontent.com/20749264/100949905-d3f10f80-353d-11eb-8f7c-60bc9a1cc9ec.png)

**Comment by piharpi** [comment]
Feel free to open a pull request :+1:
