### ISSUE TITLE
Make this compatible with GitHub Pages 

### ISSUE THREAD

**Issue by gundamdev** [piharpi/jekyll-klise#38]
I love the minimal look and it would be great to have this without the 3rd party plugin so it is able to run in Github Pages

**Comment by jadynekena** [comment]
This actually worked for me!

You can see my blogging repo [here](https://github.com/jadynekena/jadynekena.github.io), and the website going live on [https://data-addict.com](https://data-addict.com).
I used this template and I chosed the github pages environment to make it live. No vercel app or any other 3rd party tool. It's working very well. 

Feel free to clone my repo to adapt it for your own purpose.

For local dev, open the folder jadynekena.github.io (rename it to whatever you want), and see what dependencies are missing on your local server:
```
bundle install
bundle exec jekyll serve --incremental --trace
```

**Comment by anu43** [comment]
Hello @jadynekena, may I ask how you managed to have a different domain than the github.io extension?

**Comment by jadynekena** [comment]
Hello @anu43,
Sure. I bought a domain from namecheap and made it point to my repo for like 5 dollars a year.
On the repo I wrote down the right cname to make it work on the website

**Comment by anu43** [comment]
@jadynekena sorry for bothering again but you might have known something about the issue I opened https://github.com/piharpi/jekyll-klise/issues/46. Could you look at that if you would have any time? Thanks in advance!

**Comment by jadynekena** [comment]
@anu43 have you solved the issue ? seems like you closed it. Let me know if you need me to look back at it

**Comment by anu43** [comment]
To be honest, no. But instead, I decided to host it somewhere else.

**Comment by lvvittor** [comment]
Hi guys, my blog is hosted in Github Pages. You can check the source code [here](https://github.com/lvvittor/lvvittor.github.io/blob/master/.github/workflows/build-jekyll.yml).

**Comment by piharpi** [comment]
✨ Awesome guys, I think we can close the issue now

**Comment by mgztl** [comment]
> Hola chicos, mi blog está alojado en Github Pages. Puedes consultar el código fuente [aquí ](https://github.com/lvvittor/lvvittor.github.io/blob/master/.github/workflows/build-jekyll.yml).

Can I know how did you made it work? I've cloned your repo and the works, but it doesn't work when I download it and reupload...
