### ISSUE TITLE
Avoid having Google or other search engines indexing a page

### ISSUE THREAD

**Issue by garret** [piharpi/jekyll-klise#39]
I am not very expert with HTML but I would like to add the possibility to do not index a specific page/pages on search engines. 

According to this documentation (https://developers.google.com/search/docs/advanced/crawling/block-indexing) it is just needed to add  the code `<meta name="robots" content="noindex">` in the page. 

However, I guess adding such code in the markdown page will not work. Thus, is there a simple way to achieve such result? 

Thank you for the support!

**Comment by piharpi** [comment]
You need create control-flow/conditional in each pages, the control-flow is checking the frontmatter the value of `noindex: true`.

```html
<!-- put this  conditional inside of `<head>` element -->
{% if product.title == "Awesome Shoes" %}

  <meta name="robots" content="noindex">
{% endif %}
```


References
- https://shopify.github.io/liquid/tags/control-flow/

**Comment by piharpi** [comment]
You need to create control-flow/conditional in your specific page/pages, the control-flow to do is checking the frontmatter  `noindex` key is exist AND has `true` value then render the meta tag.

```html
<head>
  <!-- put this conditional inside of `<head>` element --></head>
  {% if page.noindex %}
    <meta name="robots" content="noindex">
  {% endif %}
</head>
````
then your markdown file 
```yml
---
title: "This is example title"
noindex: true # or give value `false`/leave blank if you won't render the meta tag
---
```

References
- https://shopify.github.io/liquid/tags/control-flow/
- https://jekyllrb.com/docs/front-matter/

**Comment by garret** [comment]
@piharpi Thanks! Sorry I am quite noob with html code. So should I just add it like this on the `page.html`? 

```
---
layout: compress
---

<!DOCTYPE html>
<html lang="{{ page.lang | default: site.lang | default: " en " }}">

{% include header.html %}

<head>
  <!-- put this conditional inside of `<head>` element --></head>
  {% if page.noindex %}
    <meta name="robots" content="noindex">
  {% endif %}
</head>
  
<body data-theme="{{ site.mode }}">
  {% include navbar.html %}
  <div class="wrapper">
    <header class="header">
      <h1 class="header-title center" itemprop="headline">{{ page.title | escape }}</h1>
    </header>
    <main class="page-content" aria-label="Content">
      {% include anchor_headings.html html=content anchorClass="anchor-head" beforeHeading=true h_min=4 h_max=4 %}
    </main>
    {% include footer.html %}
  </div>
</body>

</html>
```

**Comment by piharpi** [comment]
No, you need to put it inside the header.html file [`_incudes/header.html`](https://github.com/piharpi/jekyll-klise/blob/master/_includes/header.html) and don't forget to remove the head tag, because is already defined

For example
```
<head prefix="og: http://ogp.me/ns#">
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="ie=edge" />
  <!-- put this conditional inside of `<head>` element --></head>
  {% if page.noindex %}
    <meta name="robots" content="noindex">
  {% endif %}
  .....
 </head>
```

**Comment by garret** [comment]
@piharpi thanks I did as you described and it seems to work. I will close it for the moment :)

**Comment by piharpi** [comment]
> @piharpi thanks I did as you described and it seems to work. I will close it for the moment :)

You're welcome
