### ISSUE TITLE
How to keep footer at bottom?

### ISSUE THREAD

**Issue by nickresnick** [piharpi/jekyll-klise#4]
**Describe the bug**
When removing the Recent Posts section on the home page, the footer floats in the middle of the screen:

<img width="1440" alt="Screen Shot 2020-05-10 at 5 41 27 PM" src="https://user-images.githubusercontent.com/12612918/81511198-8a14b380-92e5-11ea-98af-85765fb599d3.png">

How can I keep the footer at the bottom? Have tried some solutions online but they don't work well with the html/css in this template. Thank you!

**Comment by amaksymov** [comment]
Hi! I think you can customize footer in [_layout.scss](https://github.com/piharpi/jekyll-klise/blob/master/_sass/klise/_layout.scss), like you want.
```scss
.footer {
  ... // here
}
```

**Comment by nickresnick** [comment]
thanks! do you know what css to make it stay? tried 
```
.footer {
  position: absolute;
  bottom: 0;
  width: 100%;
}
```
which i saw online, but that's not working

**Comment by nickresnick** [comment]
also tried this answer, putting the css in `_layouts.scss`: https://stackoverflow.com/a/18740003/4876432

```
* {
  margin: 0;
  padding: 0;
}

html,
body {
  height: 100%;
}

#wrap {
  min-height: 100%;
}

#main {
  overflow: auto;
  padding-bottom: 180px;
  /* must be same height as the footer */
}

#footer {
  position: relative;
  margin-top: -180px;
  /* negative value of footer height */
  height: 180px;
  clear: both;
  background-color: red;
}


/* Opera Fix thanks to Maleika (Kohoutec) */

body:before {
  content: "";
  height: 100%;
  float: left;
  width: 0;
  margin-top: -32767px;
  /* thank you Erik J - negate effect of float*/
}
```

**Comment by nickresnick** [comment]
not a great solution, but fixed it by adding
```
<head>
  <style media="screen">
    .footer {
      position: fixed;
      left: 0;
      bottom: 0;
      width: 100%;
    }
  </style>
</head>
```
to `home.html`

**Comment by piharpi** [comment]
😹️ I'm sorry, I'm too late response to this issue, feel free to create a pull request.
