### ISSUE TITLE
unknown Liquid tag error breaks GitHub Pages

### ISSUE THREAD

**Issue by rahil627** [piharpi/jekyll-klise#58]
github-pages 223 | Error:  Liquid syntax error (/tmp/jekyll-remote-theme-20220106-8-1nf7h4/_includes/header.html line 134): Unknown tag 'feed_meta' included

**Comment by AvinashReddy3108** [comment]
This is caused by the gem `jekyll-feed` not properly installed or set-up. We'd need more info on how you deployed your site to confirm this.

**Comment by rahil627** [comment]
ah you are probably right! thanks, and sorry i missed this. :( I just ended up sticking to the default minima theme and making a “skin” for that... maybe i’ll steal some css ideas from here though :P
