### ISSUE TITLE
How can I modify the symbol for the bullet points?

### ISSUE THREAD

**Issue by jchuerva** [piharpi/jekyll-klise#6]
👋 Hi!

How can I change the symbol used for the bullet points? Is it possible to use another symbol for the bullets?

![imagen](https://user-images.githubusercontent.com/5942864/82659998-d4712b00-9c29-11ea-8add-07b02840d750.png)

Thanks a lot for your help and this great theme! 🙇‍♂️

**Comment by dansch43** [comment]
Go to `_sass/klise/_base.scss` and change the content which is displayed before the `<li>`-tag:

```
// List
ul {
  list-style: none;
  li {
    display: list-item;
    text-align: -webkit-match-parent;
  }
  li::before {
    content: "\03BB"; <== Here you can insert any other unicode character
    display: inline-block;
    width: 1em;
    position: relative;
    margin-left: -1em;
    font-weight: $bold-weight;
  }
}
```

`\03BB` represents lamda: https://graphemica.com/%CE%BB

**Comment by piharpi** [comment]
> Go to `_sass/klise/_base.scss` and change the content which is displayed before the `<li>`-tag:
> 
> ```
> // List
> ul {
>   list-style: none;
>   li {
>     display: list-item;
>     text-align: -webkit-match-parent;
>   }
>   li::before {
>     content: "\03BB"; <== Here you can insert any other unicode character
>     display: inline-block;
>     width: 1em;
>     position: relative;
>     margin-left: -1em;
>     font-weight: $bold-weight;
>   }
> }
> ```
> 
> `\03BB` represents lamda: https://graphemica.com/%CE%BB

good explanation, I think it's clear.

**Comment by jchuerva** [comment]
@dansch43 thanks a lot for the clear and fast explanation! 🎉
