### ISSUE TITLE
marginissues : content length makes wrapper move left or right

### ISSUE THREAD

**Issue by mluerig** [piharpi/jekyll-klise#62]
**Describe the bug**
Depending on the length of a post or the page content, the wrapper div gets different margins: short content will produce wider margin, and long content more narrow, which, starting from left, appears to let the content "move" around.

**To Reproduce**
1. Go to main page
2. Click on first post
3. See error

**Comment by piharpi** [comment]
What browser are you using? I'm using chrome on desktop and I don't get the issue.

**Comment by piharpi** [comment]
What device/browser are you using?

**Comment by mluerig** [comment]
latest chrome, windows

sent from my phone

**Comment by mluerig** [comment]
can you reproduce this?

**Comment by mluerig** [comment]
I figures it's due the scrollbar on the right that is generated on long pages. I guess this would require a generic way to add the space that is occupied by a scrollbar - any ideas on how to do this?

**Comment by mluerig** [comment]
I came back to this and I figured the solution is here: https://stackoverflow.com/a/18548518/5238559

made a pull request

**Comment by piharpi** [comment]
Thank you, This issue closed by you @mluerig, reff to #76
