### ISSUE TITLE
I try to use it in gitlab webpages

### ISSUE THREAD

**Issue by mesteryui** [piharpi/jekyll-klise#68]
**Describe the bug**

**To Reproduce**
1. I create the gitlab repository
2. I create the .gitlab-ci.yml file 
3. The web doesn't show correctly

**Expected behavior**
That the website show correctly

**Screenshots**
![Screenshot from 2022-08-18 17-47-09](https://user-images.githubusercontent.com/108957859/185438336-50eefd10-0be0-4292-8b0e-23025c97777f.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser [Firefox]
 - Version [103]

**Smartphone (please complete the following information):**
 - Device: [Redmi Note 9 Pro]
 - OS: [Android 11]
 - Browser [Firefox]
 - Version [103]

**Additional context**

**Comment by piharpi** [comment]
I suggest you to check css file path.

**Comment by mesteryui** [comment]
I already solve the issue
