### ISSUE TITLE
Quick question. Removing "." after titles

### ISSUE THREAD

**Issue by chophilip21** [piharpi/jekyll-klise#73]
Hi, your template is really great! I am just getting started and I was wondering where I can edit to remove extra period at the end of the page titles (e.g Archive.)?

**Comment by piharpi** [comment]
Thank you mate. Did you get the solution? if you haven't found go to [jekyll-klise/_layouts/page.html](https://github.com/piharpi/jekyll-klise/blob/master/_layouts/page.html#L34) line 34 and remove the "." at the end before the `</h1>` tag closing .

**Comment by chophilip21** [comment]
I did find it already but thanks for sharing!
