### ISSUE TITLE
Can not run

### ISSUE THREAD

**Issue by daniiii5** [piharpi/jekyll-klise#88]
**Describe the bug**
Cant run the web

**To Reproduce**
Execute `bundle exec jekyll serve`

**Expected behavior**
To work

**Screenshots**
CMD output:
```
D:\daniv\Documentos\jekyll-klise-master>bundle exec jekyll serve
jekyll 4.1.1 | Error:  undefined method `[]' for nil
C:/Ruby33-x64/lib/ruby/3.3.0/logger.rb:384:in `level': undefined method `[]' for nil (NoMethodError)

    @level_override[Fiber.current] || @level
                   ^^^^^^^^^^^^^^^
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/jekyll-4.1.1/lib/jekyll/log_adapter.rb:45:in `adjust_verbosity'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/jekyll-4.1.1/lib/jekyll/configuration.rb:143:in `config_files'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/jekyll-4.1.1/lib/jekyll.rb:118:in `configuration'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/jekyll-4.1.1/lib/jekyll/command.rb:44:in `configuration_from_options'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/jekyll-4.1.1/lib/jekyll/commands/serve.rb:83:in `block (2 levels) in init_with_program'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/jekyll-4.1.1/exe/jekyll:15:in `<top (required)>'
        from C:/Ruby33-x64/bin/jekyll:25:in `load'
        from C:/Ruby33-x64/bin/jekyll:25:in `<main>'

D:\daniv\Documentos\jekyll-klise-master>
```

**Desktop (please complete the following information):**
 - OS: Windows 11 Insider Dev Preview 23612.1000
 - Browser Not needed
 - Version Not needed

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by dopewevmond** [comment]
hi @daniiii5, i had the same issue. was running ruby v3.3.0 (same as you)
- install an older version of ruby. v2.6.1 worked for me. i used ruby-install and chruby
- get a fresh clone of the repo
- cd into the folder and run `bundle install`. then `bundle exec jekyll serve`
hopefully that should work

**Comment by daniiii5** [comment]
> hi @daniiii5, i had the same issue. was running ruby v3.3.0 (same as you)
> 
> * install an older version of ruby. v2.6.1 worked for me. i used ruby-install and chruby
> * get a fresh clone of the repo
> * cd into the folder and run `bundle install`. then `bundle exec jekyll serve`
>   hopefully that should work

No need to, just changed the version of Jekyll inside the Gemfile to a newer one, that bad that problem, and it got fixed
